### ISSUE TITLE
vkdt 0.7.99-439-g0ffbf369 crashes when editig .nef file

### ISSUE THREAD

**Issue by ax006ho** [hanatos/vkdt#124] opened 2024-04-28 10:17 UTC
Steps to reproduce:

1. clone the repository
2. compile the program by 'make debug -j12'
3. execute ./vkdt -d all /nfs/photo.raw/nikon/z7ii/2024/04/20240414/_dsc2714.nef

vkdt crashes immediately, I append 

1. the log file
2. the backtrace

The system is Fedora 40 with all updates

Any help is deeply appreciated

[vkdt.log](https://github.com/hanatos/vkdt/files/15141783/vkdt.log)
[vkdt-bt-41621.txt](https://github.com/hanatos/vkdt/files/15141784/vkdt-bt-41621.txt)

**Comment by hanatos** [comment] 2024-04-28 14:53
ah good catch. of course i can't reproduce, but i just pushed something that might address whatever the validation layers complain about on your system. maybe that fixed it?

**Comment by ax006ho** [comment] 2024-04-28 16:02
First thank you for your prompt response!

Unfortunately your changes don't help.

my GNU make complained about "missing separator", so I moved line 74 - echo $(RELEASE_FILES) - right after the bin: target.

I attach the log of making the program, the log of the executionand the backtrace, hope this helps!
[make.log](https://github.com/hanatos/vkdt/files/15142685/make.log)
[vkdt.log](https://github.com/hanatos/vkdt/files/15142686/vkdt.log)
[vkdt-bt-79948.txt](https://github.com/hanatos/vkdt/files/15142687/vkdt-bt-79948.txt)

**Comment by ptilopteri** [comment] 2024-04-28 16:30
* johannes hanika ***@***.***> [04-28-24 10:54]:
> ah good catch. of course i can't reproduce, but i just pushed something that might address whatever the validation layers complain about on your system. maybe that fixed it?
> 


rawspeed module appears to be missing from current

Makefile:74: [ ()]
ls: cannot access 'src/pipe/modules/i-raw/rawspeed-*': No such file or
directory

I did "git submodule init;git submodule update"



tks,

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by ptilopteri** [comment] 2024-04-28 16:35
* paka ***@***.***> [04-28-24 12:32]:
> * johannes hanika ***@***.***> [04-28-24 10:54]:
> > ah good catch. of course i can't reproduce, but i just pushed something that might address whatever the validation layers complain about on your system. maybe that fixed it?
> > 
> 
> 
> rawspeed module appears to be missing from current
> 
> Makefile:74: [ ()]
> ls: cannot access 'src/pipe/modules/i-raw/rawspeed-*': No such file or
> directory
> 
> I did "git submodule init;git submodule update"
> 
> 
> 
> tks,

installed:	libexiv2-28 	0.28.2-226.3
		libexiv2-devel 	0.28.2-226.3


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by hanatos** [comment] 2024-04-28 16:53
okay. try again please? this gpu seems to support no features at all..

@ptilopteri rawspeed is fetched during the build process, it's not a submodule any more. the makefile had a flaw when building with rawspeed enabled. i don't test that much these days because the github ci ubuntu image is/was too old to build current rawspeed.

**Comment by ptilopteri** [comment] 2024-04-28 18:51
* johannes hanika ***@***.***> [04-28-24 12:53]:
> okay. try again please? this gpu seems to support no features at all..
> 
> @ptilopteri rawspeed is fetched during the build process, it's not a
> submodule any more.  the makefile had a flaw when building with rawspeed
> enabled.  i don't test that much these days because the github ci ubuntu
> image is/was too old to build current rawspeed.


that worked, tks

vkdt 0.7.99-451-gcf10dbf2


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by ax006ho** [comment] 2024-04-29 17:20
I'm sorry, but there is still no success. I attach

- all logs (stdout, stderr) from pull, compile and execution
- the backtrace

If I can do anything else (testing patches, ...) I would be glad to help.

As additional information:

- Execution of the Appimage from starts, but editing a raw photo shows the message: 
- vkdt as provided in https://download.opensuse.org/repositories/graphics:/darktable:/master/Fedora_Rawhide/x86_64/vkdt-0.5.9999+git204.553b1d1-105.8.x86_64.rpm (partly) 
[pce_stderr.log](https://github.com/hanatos/vkdt/files/15152537/pce_stderr.log)
[pce_stdout.log](https://github.com/hanatos/vkdt/files/15152538/pce_stdout.log)
[vkdt-bt-193413.txt](https://github.com/hanatos/vkdt/files/15152539/vkdt-bt-193413.txt)
works

**Comment by hanatos** [comment] 2024-04-29 17:57
yeah the only way you could help more is by *providing* patches.. i can't test the code path your system takes locally, so i'm pushing commits pretty much blindly, trying to disable the atomic float extensions to make the validation layers on your system happy.. if you have a minute try again the current version please.

**Comment by hanatos** [comment] 2024-04-29 19:07
progress. this seems to be a different error now. it doesn't find rawspeed's cameras.xml. do you have such a file? are you using `make install` or just make and are you running inside the bin/ directory or top level?

**Comment by hanatos** [comment] 2024-06-16 17:50
.. that last error is some validation layer complaint that might have been fixed in the meantime. does it run nowadays?

**Comment by ax006ho** [comment] 2024-06-19 11:00
Unfortunately no. It depends on the circumstances.

If I compile it following the readme.md, the program starts, it breaks whenever I move the mouse to do some action (crop, ...). The logs are

[pce_stderr_master.log](https://github.com/user-attachments/files/15897163/pce_stderr_master.log)
[pce_stdout_master.log](https://github.com/user-attachments/files/15897165/pce_stdout_master.log)
[vkdt-bt-212069.txt](https://github.com/user-attachments/files/15897168/vkdt-bt-212069.txt)

The *_stderr_* log files show the error messages of the compilation, the  *_stdout_* log files show the messages of the execution.

I've inserted some debug messages to have a better insight in what's going on, but adding these leads to another error:

[pce_stderr_JHf.log](https://github.com/user-attachments/files/15897207/pce_stderr_JHf.log)
[pce_stdout_JHf.log](https://github.com/user-attachments/files/15897208/pce_stdout_JHf.log)
[vkdt-bt-205878.txt](https://github.com/user-attachments/files/15897209/vkdt-bt-205878.txt)

In my experience, this indicates problems with memory organisation, but this is only a conservative estimate.

**Comment by ax006ho** [comment] 2024-06-25 15:15
Just a remark...

Compiling vkdt requires swresample.pc

Fedora 40 only provides
/usr/lib64/pkgconfig/libswresample.pc

so I've made a link to
/usr/local/lib64/pkgconfig/swresample.pc

and the requirement was fulfilled

**Comment by ptilopteri** [comment] 2024-06-25 16:28
* ax006ho ***@***.***> [06-25-24 11:16]:
> Just a remark...
> 
> Compiling vkdt requires swresample.pc
> 
> Fedora 40 only provides
> /usr/lib64/pkgconfig/libswresample.pc
> 
> so I've made a link to
> /usr/local/lib64/pkgconfig/swresample.pc
> 
> and the requirement was fulfilled

I compile vkdt on openSUSE Tumbleweed and have no "swresample.pc"

??


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by hanatos** [comment] 2024-06-30 07:59
ah thanks, that's a mistake in the default build config. it should be libswresample instead of swresample. fix pushed.

as a side note, the logs would be much more readable if you'd just put stderr and stdout into the same file, like `2>&1 > something.log` kinda thing.

that last thing you posted is not a crash but a failed assertion due to a validation layer complaint.

why is your log full of c++ output? which gpu hardware + driver and which version is this?

**Comment by ax006ho** [comment] 2024-06-30 19:12
Answered by private communication, appended is the current
 .log-file fulfilling the requirements

[vkdt-bt-46440.txt](https://github.com/user-attachments/files/16045816/vkdt-bt-46440.txt)
[pce_stdout_master.log](https://github.com/user-attachments/files/16045817/pce_stdout_master.log)

**Comment by ax006ho** [comment] 2024-07-02 05:46
Success! The version 0.8.99-58-g54456d8a shows the correct picture and I can use one or two buttons.

There are some more glitches but I would say that you can close this thread. I will do more tests later and write down, what works or not, if that's fine for you.

**Comment by hanatos** [comment] 2024-07-02 06:52
yay :D absolutely, do let me know if you encounter any other oddities.

**Closed** 2024-07-03 07:50 UTC
